# Generated by Django 4.1 on 2023-05-30 06:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_rename_blog_title_blog_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='brief',
        ),
    ]
