# Generated by Django 4.1 on 2023-05-31 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='introduction',
            field=models.TextField(default='introduction', max_length=4000),
        ),
        migrations.AddField(
            model_name='project',
            name='paper',
            field=models.TextField(default='paper', max_length=4000),
        ),
        migrations.AddField(
            model_name='project',
            name='tutorial',
            field=models.TextField(default='tutorial', max_length=4000),
        ),
    ]
