# Generated by Django 4.1 on 2023-05-31 08:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_project_introduction_project_paper_project_tutorial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 31, 8, 36, 36, 331823, tzinfo=datetime.timezone.utc), verbose_name='data published'),
        ),
    ]
