# Generated by Django 4.1 on 2023-06-01 08:20

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0005_remove_user_id_alter_project_pub_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 1, 8, 20, 57, 427873, tzinfo=datetime.timezone.utc), verbose_name='data published'),
        ),
        migrations.AlterField(
            model_name='user',
            name='project',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='project.project'),
        ),
    ]
