# Generated by Django 4.1 on 2023-06-01 09:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0006_alter_project_pub_date_alter_user_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 1, 9, 14, 5, 709319, tzinfo=datetime.timezone.utc), verbose_name='data published'),
        ),
        migrations.RemoveField(
            model_name='user',
            name='project',
        ),
        migrations.AddField(
            model_name='user',
            name='project',
            field=models.ManyToManyField(to='project.project'),
        ),
    ]
