# Generated by Django 4.1 on 2023-06-05 13:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0011_project_price_alter_project_pub_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='introduction',
            field=models.TextField(default='introduction'),
        ),
        migrations.AlterField(
            model_name='project',
            name='paper',
            field=models.TextField(default='paper'),
        ),
        migrations.AlterField(
            model_name='project',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 5, 13, 48, 16, 572545, tzinfo=datetime.timezone.utc), verbose_name='data published'),
        ),
        migrations.AlterField(
            model_name='project',
            name='tutorial',
            field=models.TextField(default='tutorial'),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 5, 13, 48, 16, 572545, tzinfo=datetime.timezone.utc), verbose_name='purchase date'),
        ),
    ]
