# Generated by Django 4.1 on 2023-06-16 02:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0013_alter_project_price_alter_project_pub_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='visit_code',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='project',
            name='visit_intro',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='project',
            name='visit_paper',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='project',
            name='visit_tutorial',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='login_times',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='project',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 16, 2, 2, 49, 62769, tzinfo=datetime.timezone.utc), verbose_name='data published'),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 16, 2, 2, 49, 63768, tzinfo=datetime.timezone.utc), verbose_name='purchase date'),
        ),
    ]
