# Generated by Django 4.1 on 2023-07-19 08:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0015_project_brief_alter_project_pub_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='paper',
        ),
        migrations.RemoveField(
            model_name='project',
            name='visit_code',
        ),
        migrations.RemoveField(
            model_name='project',
            name='visit_intro',
        ),
        migrations.RemoveField(
            model_name='project',
            name='visit_paper',
        ),
        migrations.RemoveField(
            model_name='project',
            name='visit_tutorial',
        ),
        migrations.AlterField(
            model_name='project',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 19, 8, 40, 52, 693093, tzinfo=datetime.timezone.utc), verbose_name='data published'),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 19, 8, 40, 52, 696097, tzinfo=datetime.timezone.utc), verbose_name='purchase date'),
        ),
    ]
