# Generated by Django 4.1 on 2023-07-26 07:20

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0016_remove_project_paper_remove_project_visit_code_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='project',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 26, 7, 19, 7, 587082, tzinfo=datetime.timezone.utc), verbose_name='data published'),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 26, 7, 19, 7, 589084, tzinfo=datetime.timezone.utc), verbose_name='purchase date'),
        ),
        migrations.AddField(
            model_name='purchase',
            name='order_id',
            field=models.ForeignKey(default=245, on_delete=django.db.models.deletion.CASCADE, to='project.order'),
            preserve_default=False,
        ),
    ]
