# Generated by Django 4.1 on 2023-07-26 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0017_order_alter_project_pub_date_alter_purchase_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchase',
            old_name='order_id',
            new_name='order',
        ),
        migrations.RemoveField(
            model_name='project',
            name='pub_date',
        ),
        migrations.RemoveField(
            model_name='purchase',
            name='date',
        ),
    ]
