# Generated by Django 4.1 on 2023-07-30 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0020_alter_user_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='prj_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
