# Generated by Django 4.1 on 2023-08-02 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0022_user_field_user_school'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='brief',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='project',
            name='price',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='user',
            name='field',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='school',
            field=models.CharField(default='', max_length=20),
        ),
    ]
