# Generated by Django 4.1 on 2023-08-02 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0023_alter_project_brief_alter_project_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='field',
        ),
        migrations.RemoveField(
            model_name='user',
            name='school',
        ),
        migrations.AddField(
            model_name='user',
            name='tel',
            field=models.CharField(default='', max_length=11),
        ),
    ]
