# Generated by Django 4.1 on 2023-08-02 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0024_remove_user_field_remove_user_school_user_tel'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='bid_times',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='win_times',
            field=models.IntegerField(default=0),
        ),
    ]
