# Generated by Django 4.1 on 2023-08-02 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0025_user_bid_times_user_win_times'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='positive_times',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='pub_times',
            field=models.IntegerField(default=0),
        ),
    ]
