# Generated by Django 4.1 on 2023-08-17 07:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0026_user_positive_times_user_pub_times'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='positive_times',
        ),
    ]
