# Generated by Django 4.1 on 2023-08-02 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('help', '0002_request_type_alter_request_content_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='lowest_bid',
            field=models.CharField(default='-', max_length=10),
        ),
        migrations.AddField(
            model_name='request',
            name='num_bid',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='request',
            name='num_comment',
            field=models.IntegerField(default=0),
        ),
    ]
