# Generated by Django 4.1 on 2023-08-02 13:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('help', '0003_request_lowest_bid_request_num_bid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='datetime',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
