# Generated by Django 4.1 on 2023-08-02 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('help', '0004_request_datetime'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestfollows',
            name='notify_new_bids',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
