# Generated by Django 4.1 on 2023-08-03 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('help', '0005_requestfollows_notify_new_bids'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestfollows',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
