# Generated by Django 4.1 on 2023-08-03 01:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('help', '0006_alter_requestfollows_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='request',
            old_name='id',
            new_name='req_id',
        ),
        migrations.RenameField(
            model_name='requestfollows',
            old_name='id',
            new_name='fol_id',
        ),
        migrations.RemoveField(
            model_name='request',
            name='hits',
        ),
    ]
