# Generated by Django 4.1 on 2023-08-03 01:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('help', '0007_rename_id_request_req_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='request',
            old_name='req_id',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='requestfollows',
            old_name='fol_id',
            new_name='id',
        ),
    ]
