# Generated by Django 4.1 on 2023-08-04 15:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('help', '0009_procedure_remove_requestfollows_notify_new_bids_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestfollows',
            name='procedure',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='help.procedure'),
            preserve_default=False,
        ),
    ]
