# Generated by Django 4.1 on 2023-08-05 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('help', '0011_cooperation_procedurestep_state_cooperationmessage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='procedurestep',
            name='state',
        ),
        migrations.AddField(
            model_name='cooperation',
            name='active',
            field=models.IntegerField(default=0),
        ),
    ]
