# Generated by Django 4.1 on 2023-08-05 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('help', '0012_remove_procedurestep_state_cooperation_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='cooperation',
            name='request_document',
            field=models.CharField(default='', max_length=2000),
        ),
    ]
