# Generated by Django 4.1 on 2023-08-05 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('help', '0013_cooperation_request_document'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cooperation',
            name='request_document',
            field=models.CharField(default='# 这是一级标题\n## 这是二级标题\n### 这是三级标题\n这是正文', max_length=2000),
        ),
    ]
