# Generated by Django 4.1 on 2023-08-06 00:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('help', '0014_alter_cooperation_request_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='cooperation',
            name='request_document_update_datetime',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 6, 0, 52, 1, 497772, tzinfo=datetime.timezone.utc)),
        ),
    ]
