# Generated by Django 4.1 on 2023-08-06 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('help', '0015_cooperation_request_document_update_datetime'),
    ]

    operations = [
        migrations.AddField(
            model_name='cooperation',
            name='request_document_update',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='cooperation',
            name='request_document_update_datetime',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
