# Generated by Django 4.1 on 2023-08-06 05:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('help', '0016_cooperation_request_document_update_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cooperation',
            name='predict_finish_date',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='cooperation',
            name='request_document_update_datetime',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 6, 5, 43, 46, 725106, tzinfo=datetime.timezone.utc)),
        ),
    ]
