# Generated by Django 4.1 on 2023-08-06 06:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('help', '0017_cooperation_predict_finish_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cooperation',
            name='predict_finish_date_fix',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='cooperation',
            name='request_document_update_datetime',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 6, 6, 59, 43, 832750, tzinfo=datetime.timezone.utc)),
        ),
    ]
