# Generated by Django 4.1 on 2023-08-06 07:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('help', '0018_cooperation_predict_finish_date_fix_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cooperation',
            name='predict_finish_date_fix_state',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='cooperation',
            name='predict_finish_date',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='cooperation',
            name='predict_finish_date_fix',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='cooperation',
            name='request_document_update_datetime',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 6, 7, 56, 22, 813383, tzinfo=datetime.timezone.utc)),
        ),
    ]
