# Generated by Django 4.1 on 2023-08-06 08:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('help', '0019_cooperation_predict_finish_date_fix_state_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cooperation',
            name='request_document_update_datetime',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 6, 8, 3, 38, 808461, tzinfo=datetime.timezone.utc)),
        ),
    ]
