# Generated by Django 4.1 on 2023-08-07 02:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('help', '0020_alter_cooperation_request_document_update_datetime'),
    ]

    operations = [
        migrations.AddField(
            model_name='cooperation',
            name='acceptance_date',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='cooperation',
            name='acceptance_date_fix',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='cooperation',
            name='acceptance_date_fix_state',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='cooperation',
            name='request_document_update_datetime',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 7, 2, 49, 34, 299896, tzinfo=datetime.timezone.utc)),
        ),
    ]
