# Generated by Django 4.1 on 2023-08-09 11:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('help', '0022_cooperationchatmessage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cooperation',
            name='request_document_update_datetime',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 9, 11, 8, 19, 70713, tzinfo=datetime.timezone.utc)),
        ),
    ]
