# Generated by Django 4.1 on 2023-08-09 12:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('help', '0023_alter_cooperation_request_document_update_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cooperation',
            name='request_document_update_datetime',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 9, 12, 4, 54, 422321, tzinfo=datetime.timezone.utc)),
        ),
        migrations.DeleteModel(
            name='CooperationChatMessage',
        ),
    ]
