# Generated by Django 4.1 on 2023-08-16 01:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('help', '0027_alter_cooperation_client_deposit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cooperation',
            name='client_deposit',
            field=models.IntegerField(default=-1),
        ),
        migrations.AlterField(
            model_name='cooperation',
            name='request_document_update_datetime',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 16, 1, 15, 12, 379693, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='cooperation',
            name='server_deposit',
            field=models.IntegerField(default=-1),
        ),
    ]
