# Generated by Django 4.1 on 2023-08-16 01:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('help', '0029_alter_cooperation_client_deposit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cooperation',
            name='request_document_update_datetime',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 16, 1, 25, 23, 867237, tzinfo=datetime.timezone.utc)),
        ),
    ]
