# Generated by Django 4.1 on 2023-08-16 01:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('help', '0030_alter_cooperation_request_document_update_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cooperation',
            name='request_document_update_datetime',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 16, 1, 31, 42, 27920, tzinfo=datetime.timezone.utc)),
        ),
    ]
