# Generated by Django 4.1 on 2023-08-16 07:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('help', '0031_alter_cooperation_request_document_update_datetime'),
    ]

    operations = [
        migrations.AddField(
            model_name='cooperation',
            name='client_alipay_id',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='cooperation',
            name='client_pay_method',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='cooperation',
            name='client_wechat_id',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='cooperation',
            name='server_alipay_id',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='cooperation',
            name='server_pay_method',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='cooperation',
            name='server_wechat_id',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='cooperation',
            name='request_document_update_datetime',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 16, 7, 12, 6, 651892, tzinfo=datetime.timezone.utc)),
        ),
    ]
