# Generated by Django 4.1 on 2023-08-16 08:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('help', '0032_cooperation_client_alipay_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cooperation',
            name='client_pay_method',
        ),
        migrations.RemoveField(
            model_name='cooperation',
            name='server_pay_method',
        ),
        migrations.AddField(
            model_name='cooperation',
            name='client_cancel',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cooperation',
            name='server_cancel',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='cooperation',
            name='request_document_update_datetime',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 16, 8, 7, 59, 948862, tzinfo=datetime.timezone.utc)),
        ),
    ]
