# Generated by Django 4.1 on 2023-08-17 06:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('help', '0033_remove_cooperation_client_pay_method_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cooperation',
            name='client_rate',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='cooperation',
            name='client_review',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='cooperation',
            name='server_rate',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='cooperation',
            name='server_review',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='cooperation',
            name='request_document_update_datetime',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 17, 6, 56, 28, 865353, tzinfo=datetime.timezone.utc)),
        ),
    ]
