# Generated by Django 4.1 on 2023-08-17 07:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('help', '0034_cooperation_client_rate_cooperation_client_review_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cooperation',
            name='client_alipay_id',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='cooperation',
            name='client_review',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='cooperation',
            name='client_wechat_id',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='cooperation',
            name='request_document_update_datetime',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 17, 7, 4, 20, 478984, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='cooperation',
            name='server_alipay_id',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='cooperation',
            name='server_review',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='cooperation',
            name='server_wechat_id',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
    ]
