# Generated by Django 4.1 on 2023-08-17 07:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('help', '0035_alter_cooperation_client_alipay_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cooperation',
            name='request_document_update_datetime',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 17, 7, 43, 44, 287990, tzinfo=datetime.timezone.utc)),
        ),
    ]
