# Generated by Django 4.1 on 2023-08-17 08:08

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0027_remove_user_positive_times'),
        ('help', '0036_alter_cooperation_request_document_update_datetime'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cooperation',
            name='client_rate',
        ),
        migrations.RemoveField(
            model_name='cooperation',
            name='client_review',
        ),
        migrations.RemoveField(
            model_name='cooperation',
            name='server_rate',
        ),
        migrations.RemoveField(
            model_name='cooperation',
            name='server_review',
        ),
        migrations.AlterField(
            model_name='cooperation',
            name='request_document_update_datetime',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 17, 8, 8, 18, 251447, tzinfo=datetime.timezone.utc)),
        ),
        migrations.CreateModel(
            name='ServerFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.FloatField()),
                ('review', models.CharField(max_length=100)),
                ('coop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='help.cooperation')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.user')),
            ],
        ),
        migrations.CreateModel(
            name='ClientFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.FloatField()),
                ('review', models.CharField(max_length=100)),
                ('coop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='help.cooperation')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.user')),
            ],
        ),
    ]
