# Generated by Django 4.1 on 2023-08-17 13:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('help', '0037_remove_cooperation_client_rate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientfeedback',
            name='date',
            field=models.DateField(default=datetime.datetime(2023, 8, 17, 13, 27, 58, 127022, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='serverfeedback',
            name='date',
            field=models.DateField(default=datetime.datetime(2023, 8, 17, 13, 28, 2, 379357, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cooperation',
            name='request_document_update_datetime',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 17, 13, 27, 25, 149909, tzinfo=datetime.timezone.utc)),
        ),
    ]
