# Generated by Django 4.1 on 2023-08-17 13:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('help', '0038_clientfeedback_date_serverfeedback_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cooperation',
            name='request_document_update_datetime',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 17, 13, 43, 30, 766807, tzinfo=datetime.timezone.utc)),
        ),
    ]
