# Generated by Django 4.1 on 2023-08-18 05:15

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('help', '0039_alter_cooperation_request_document_update_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cooperation',
            name='request_document_update_datetime',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 18, 5, 15, 29, 354555, tzinfo=datetime.timezone.utc)),
        ),
        migrations.CreateModel(
            name='CooperationAppealing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='help.cooperation')),
            ],
        ),
    ]
