# Generated by Django 4.1 on 2023-08-18 05:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('help', '0040_alter_cooperation_request_document_update_datetime_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cooperation',
            name='request_document_update_datetime',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 18, 5, 36, 6, 136693, tzinfo=datetime.timezone.utc)),
        ),
    ]
