# Generated by Django 4.1 on 2023-08-18 05:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('help', '0041_alter_cooperation_request_document_update_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cooperation',
            name='request_document_update_datetime',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 18, 5, 40, 24, 671715, tzinfo=datetime.timezone.utc)),
        ),
    ]
