# Generated by Django 4.1 on 2023-08-18 05:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('help', '0042_alter_cooperation_request_document_update_datetime'),
    ]

    operations = [
        migrations.AddField(
            model_name='cooperation',
            name='is_appeal',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='cooperation',
            name='request_document_update_datetime',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 18, 5, 58, 45, 427660, tzinfo=datetime.timezone.utc)),
        ),
    ]
