# Generated by Django 4.1 on 2023-08-19 07:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('help', '0044_cooperationappealing_expect_result_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CooperationPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step', models.IntegerField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=6)),
                ('datetime', models.DateTimeField()),
                ('transfer', models.BooleanField(default=False)),
                ('coop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='help.cooperation')),
            ],
        ),
    ]
